version: '3'

services:
  bot:
    build: Bot/
#    restart: always

  flask_admin:
    build: FlaskAdmin/
#    restart: always
    depends_on:
      - postgres
    ports:
      - 5000:5000
    environment:
      - TZ=Europe/Moscow
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD

  postgres:
    image: postgres:11-alpine
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - 5432:5432
    volumes:
      - ./postgresql/dumps:/code/dumps
      - ./postgresql/data:/var/lib/postgresql/data
