"""empty message

Revision ID: 06741f56fb1a
Revises: 
Create Date: 2021-01-28 00:37:35.087077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06741f56fb1a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('command',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Ключ', sa.String(length=256), nullable=True),
    sa.Column('Название', sa.String(length=256), nullable=True),
    sa.Column('Контент', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Ключ')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('command')
    # ### end Alembic commands ###
